#!venv/bin/python

import argparse
import sys

from facebook_crawler import FacebookCrawler
from twitter_crawler import TwitterCrawler


def parse_arguments():
    parser = argparse.ArgumentParser(description='')

    parser.add_argument('-fb_token', dest='fb_token', help="User's Facebook Access Token (String)")
    parser.add_argument('-tw_token', dest='tw_token', help="User's Twitter Access Token (String)")
    parser.add_argument('-tw_secret', dest='tw_secret', help="User's Twitter Access Token Secret (String)")

    args = parser.parse_args()

    if (args.tw_token is not None and args.tw_secret is None) or (args.tw_token is None and args.tw_secret is not None):
        print("ERROR: Missing Twitter's Access Token or Twitter's Token Secret.")
        parser.print_help(sys.stderr)

    return args


def download_tw_information(tw_token, tw_secret):

    twitter = TwitterCrawler(tw_token, tw_secret)
    twitter.get_profile()
    twitter.get_followers()
    twitter.get_friends()
    twitter.get_tweets()
    twitter.get_favorites()


def download_fb_information(fb_token):
    fb = FacebookCrawler(fb_token)

    fb.get_user()

    fb.get_posts()
    fb.get_tagged_posts()

    fb.get_uploaded_photos()
    fb.get_tagged_photos()

    fb.get_uploaded_videos()
    fb.get_tagged_videos()

    fb.get_liked_pages()

    fb.get_listened_musics()
    fb.get_watched_videos()
    fb.get_read_books()


if __name__ == '__main__':

    args = parse_arguments()

    if args.fb_token is not None:
        download_fb_information(args.fb_token)

    if args.tw_token is not None and args.tw_secret is not None:
        download_tw_information(args.tw_token, args.tw_secret)
